name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        poetry-version: ["1.5.0"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install poetry ${{ matrix.poetry-version }}
      run: pipx install poetry==${{ matrix.poetry-version }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: poetry install

    - name: Test with pytest
      run: |
        poetry run python -m pytest -v tests
      env:
          OURA_PERSONAL_ACCESS_TOKEN: ${{ secrets.OURA_PERSONAL_ACCESS_TOKEN }}
