# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/qself',
                'doc_host': 'https://JungeAlexander.github.io',
                'git_url': 'https://github.com/JungeAlexander/qself',
                'lib_path': 'qself'},
  'syms': {'qself.core': {'qself.core.foo': ('core.html#foo', 'qself/core.py')}}}